### ISSUE TITLE
Stacktrace logged in case HTTP(s)_PROXY is set without password

### ISSUE THREAD

**Issue by ca-stefan-cordes** [mulesoft/mule-maven-plugin#352]
The new 
/mule-maven-plugin-parent/mule-maven-plugin/src/main/java/org/mule/tools/maven/config/proxy/ProxyConfiguration.java
(since MMP-512 - Support deployment using proxies 3.x (#330))

is checking whether HTTP_PROXY is set (isAbleToSetupProxy) but then it throws a NoSuchFieldException in case password or port is missing (btw. should replace & with &&)

That exception
```
[INFO] --- mule-maven-plugin:3.3.6:deploy (default-cli) @ dt0b35-mule-template-test-m4 ---
[ERROR] Fail to configure proxy settings.
java.lang.NoSuchFieldException: Missing proxy configuration.
	at org.mule.tools.maven.config.proxy.ProxyConfiguration.buildProxyFromProperties(ProxyConfiguration.java:108)
	at org.mule.tools.maven.config.proxy.ProxyConfiguration.getProxy(ProxyConfiguration.java:90)
	at org.mule.tools.maven.config.proxy.ProxyConfiguration.handleProxySettings(ProxyConfiguration.java:44)
 	at org.mule.tools.maven.mojo.deploy.AbstractMuleDeployerMojo.setupProxy(AbstractMuleDeployerMojo.java:141)
	at org.mule.tools.maven.mojo.deploy.AbstractMuleDeployerMojo.execute(AbstractMuleDeployerMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)

```

later on is ignored in AbstractMuleDeployerMojo.setupProxy().

Deployment works as expected and Maven Build exits with 

```
[INFO] BUILD SUCCESS
```

Even the mule.ProxyConfiguration fails the http request is correctly performed with the env.HTTPS_PROXY configuration (without authentication) later on in the http libraries (either via Apache/Grizzly - I did not check which one is used...)

As the only purpose of ProxyConfiguration is to fill the java.net.Authenticator
a less verbose message "Proxy User/Password not set" would be sufficient.

**Comment by julianpascualMuleSoft** [comment]
Fied on #360

**Comment by ca-stefan-cordes** [comment]
Thanks.
