### ISSUE TITLE
undeploy fails with IOException

### ISSUE THREAD

**Issue by hxs8839** [mulesoft/mule-maven-plugin#5]
When stopping mule standalone server (version 3.4.1), the undeploy execution fails with the stacktrace below:

Caused by: org.apache.maven.plugin.MojoExecutionException: Could not delete directory [../<project>/target/mule-standalone-3.4.1/apps/<appName>]
	at org.mule.tools.maven.plugin.mule.Undeployer.undeploy(Undeployer.java:72)
	at org.mule.tools.maven.plugin.mule.Undeployer.execute(Undeployer.java:43)
	at org.mule.tools.maven.plugin.mule.UndeployMojo.standalone(UndeployMojo.java:123)
	at org.mule.tools.maven.plugin.mule.UndeployMojo.doExecute(UndeployMojo.java:38)
	at org.mule.tools.maven.plugin.mule.AbstractMuleMojo.execute(AbstractMuleMojo.java:176)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 30 more
Caused by: java.io.IOException: Unable to delete directory../<project>/target/mule-standalone-3.4.1/apps/<appName>/lib.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.mule.tools.maven.plugin.mule.Undeployer.undeploy(Undeployer.java:66)
	... 36 more
Would it be better if we use FileDeleteStrategy.FORCE.deleteQuietly(file) so that there's no exception thrown and the next time we do a maven clean verify, the target directories get deleted and we have a clean slate?

**Comment by amatety10** [comment]
To add more context, this seems to be happening when running on Jenkins utilizing a NFS mount. Looks like the code is deleting the app without first stopping the server which results in .nfsxxxyyy files being written in the apps/<app1>/lib directory. This results in the failure.
