### ISSUE TITLE
Specify application’s filepath by <application> in cloudhub deployment causes invalid domain error

### ISSUE THREAD

**Issue by ykyuen** [mulesoft/mule-maven-plugin#65]
Version: 2.2.1

According to the [documentation](https://docs.mulesoft.com/mule-user-guide/v/3.8/mule-maven-plugin#cloudhub), the `<application>` set in the plugin configuration is for specifying the artifact file path. i found that if i only include `<application>` without `<applicationName>`, the deployment will failed due to the following error.
```
[ERROR] Failed: 400 Bad Request: {"message":"Domains can only contain upto 42 alpha numeric characters and dashes and cannot end with a dash."}
[ERROR] Failed to deploy abc.zip: Failed to deploy application abc.zip
org.mule.tools.maven.plugin.mule.DeploymentException: Failed to deploy application abc.zip
	at org.mule.tools.maven.plugin.mule.cloudhub.CloudhubDeployer.deploy(CloudhubDeployer.java:102)
	at org.mule.tools.maven.plugin.mule.DeployMojo.deployWithDeployer(DeployMojo.java:194)
	at org.mule.tools.maven.plugin.mule.DeployMojo.cloudhub(DeployMojo.java:171)
	at org.mule.tools.maven.plugin.mule.DeployMojo.doExecute(DeployMojo.java:157)
	at org.mule.tools.maven.plugin.mule.AbstractMuleMojo.execute(AbstractMuleMojo.java:214)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.mule.tools.maven.plugin.mule.ApiException: 400 Bad Request: {"message":"Domains can only contain upto 42 alpha numeric characters and dashes and cannot end with a dash."}
	at org.mule.tools.maven.plugin.mule.cloudhub.CloudhubApi.isNameAvailable(CloudhubApi.java:207)
	at org.mule.tools.maven.plugin.mule.cloudhub.CloudhubDeployer.deploy(CloudhubDeployer.java:64)
	... 26 more
```

On the other hand, if i include `applicationName` in the plugin configuration, the deployment works fine.

So these two configs have to go together?

**Comment by Sjnahak** [comment]
we faced the same issue and found that value of applicationName was more than 42 characters , So reduced the number characters in  applicationName which solved the issue.
